/************************************************************/
/**              File generated by asset_packer            **/
/************************************************************/

// Created: Sat Feb 17 02:17:45 2018
// Version: 0

#pragma once

enum rdge_asset_pack_table
{
    rdge_asset_surface_overworld_bg = 0,
    rdge_asset_surface_animals = 1,
    rdge_asset_surface_overworld_obj = 2,
    rdge_asset_surface_player = 3,
    rdge_asset_spritesheet_player = 4,
    rdge_asset_spritesheet_animals = 5,
    rdge_asset_spritesheet_overworld_obj = 6,
    rdge_asset_tileset_overworld_bg = 7,
    rdge_asset_tilemap_overworld = 8,
};

enum player_spritesheet_frames
{
    frame_player_attack_back_1 = 0,
    frame_player_attack_back_2 = 1,
    frame_player_attack_back_3 = 2,
    frame_player_attack_back_4 = 3,
    frame_player_attack_back_5 = 4,
    frame_player_attack_front_1 = 5,
    frame_player_attack_front_2 = 6,
    frame_player_attack_front_3 = 7,
    frame_player_attack_front_4 = 8,
    frame_player_attack_front_5 = 9,
    frame_player_attack_side_1 = 10,
    frame_player_attack_side_2 = 11,
    frame_player_attack_side_3 = 12,
    frame_player_attack_side_4 = 13,
    frame_player_attack_side_5 = 14,
    frame_player_fight_idle_back_1 = 15,
    frame_player_fight_idle_back_2 = 16,
    frame_player_fight_idle_back_3 = 17,
    frame_player_fight_idle_front_1 = 18,
    frame_player_fight_idle_front_2 = 19,
    frame_player_fight_idle_front_3 = 20,
    frame_player_fight_idle_side_1 = 21,
    frame_player_fight_idle_side_2 = 22,
    frame_player_fight_idle_side_3 = 23,
    frame_player_idle_back_1 = 24,
    frame_player_idle_front_1 = 25,
    frame_player_idle_front_2 = 26,
    frame_player_idle_front_3 = 27,
    frame_player_idle_side_1 = 28,
    frame_player_idle_side_2 = 29,
    frame_player_idle_side_3 = 30,
    frame_player_run_back_1 = 31,
    frame_player_run_back_2 = 32,
    frame_player_run_front_1 = 33,
    frame_player_run_front_2 = 34,
    frame_player_run_side_1 = 35,
    frame_player_run_side_2 = 36,
    frame_player_sheathe_back_1 = 37,
    frame_player_sheathe_back_2 = 38,
    frame_player_sheathe_back_3 = 39,
    frame_player_sheathe_front_1 = 40,
    frame_player_sheathe_front_2 = 41,
    frame_player_sheathe_front_3 = 42,
    frame_player_sheathe_side_1 = 43,
    frame_player_sheathe_side_2 = 44,
    frame_player_sheathe_side_3 = 45,
    frame_player_walk_back_1 = 46,
    frame_player_walk_back_2 = 47,
    frame_player_walk_back_3 = 48,
    frame_player_walk_back_4 = 49,
    frame_player_walk_back_5 = 50,
    frame_player_walk_back_6 = 51,
    frame_player_walk_front_1 = 52,
    frame_player_walk_front_2 = 53,
    frame_player_walk_front_3 = 54,
    frame_player_walk_front_4 = 55,
    frame_player_walk_front_5 = 56,
    frame_player_walk_front_6 = 57,
    frame_player_walk_side_1 = 58,
    frame_player_walk_side_2 = 59,
    frame_player_walk_side_3 = 60,
    frame_player_walk_side_4 = 61,
    frame_player_walk_side_5 = 62,
    frame_player_walk_side_6 = 63,
};

enum player_spritesheet_animations
{
    animation_player_idle_front = 0,
    animation_player_idle_back = 1,
    animation_player_idle_right = 2,
    animation_player_idle_left = 3,
    animation_player_walk_front = 4,
    animation_player_walk_back = 5,
    animation_player_walk_right = 6,
    animation_player_walk_left = 7,
    animation_player_run_front = 8,
    animation_player_run_back = 9,
    animation_player_run_right = 10,
    animation_player_run_left = 11,
    animation_player_sheathe_front = 12,
    animation_player_sheathe_back = 13,
    animation_player_sheathe_right = 14,
    animation_player_sheathe_left = 15,
    animation_player_fight_idle_front = 16,
    animation_player_fight_idle_back = 17,
    animation_player_fight_idle_right = 18,
    animation_player_fight_idle_left = 19,
    animation_player_attack_front = 20,
    animation_player_attack_back = 21,
    animation_player_attack_right = 22,
    animation_player_attack_left = 23,
};

enum animals_spritesheet_frames
{
    frame_animals_mallard_baby_squint_front_1 = 0,
    frame_animals_mallard_baby_squint_front_2 = 1,
    frame_animals_mallard_baby_squint_side_1 = 2,
    frame_animals_mallard_baby_squint_side_2 = 3,
    frame_animals_mallard_baby_walk_back_1 = 4,
    frame_animals_mallard_baby_walk_back_2 = 5,
    frame_animals_mallard_baby_walk_front_1 = 6,
    frame_animals_mallard_baby_walk_front_2 = 7,
    frame_animals_mallard_baby_walk_side_1 = 8,
    frame_animals_mallard_baby_walk_side_2 = 9,
    frame_animals_seagull_fly_side_1 = 10,
    frame_animals_seagull_fly_side_2 = 11,
    frame_animals_seagull_fly_side_3 = 12,
    frame_animals_seagull_fly_side_4 = 13,
    frame_animals_seagull_fly_side_5 = 14,
    frame_animals_seagull_fly_side_6 = 15,
    frame_animals_seagull_fly_side_7 = 16,
};

enum animals_spritesheet_animations
{
    animation_animals_mallard_baby_walk_front = 0,
    animation_animals_mallard_baby_walk_back = 1,
    animation_animals_mallard_baby_walk_right = 2,
    animation_animals_mallard_baby_walk_left = 3,
    animation_animals_seagull_fly_left = 4,
    animation_animals_seagull_fly_right = 5,
};

enum overworld_obj_spritesheet_frames
{
    frame_bush_01 = 2,
    frame_bush_02 = 3,
    frame_bush_03 = 4,
    frame_chop_block_02 = 5,
    frame_chop_block_03 = 6,
    frame_flower_pot_01 = 1,
    frame_stone_01 = 7,
    frame_stone_02 = 8,
    frame_tree_01 = 0,
    frame_tree_02 = 9,
};

enum overworld_tilemap_layers
{
    overworld_layer_bg = 0,
    overworld_layer_bg_overlay_1 = 1,
    overworld_layer_bg_overlay_2 = 2,
    overworld_layer_bg_collision = 3,
    overworld_layer_bg_sprites = 4,
    overworld_layer_temp = 5,
};

