#pragma once

#include <rdge/core.hpp>
#include <chrono/events.hpp>

//!@{ Forward declarations
namespace rdge {
class Game;
class PackFile;
} // namespace rdge
//!@}

//! \struct game_ratios
//! \details Different ratios and scales to convert the different ways the game
//!          is represented.  Types are broken down into:
//!            - base - External (from assets)
//!            - world - Physics world
//!            - screen - Rendering pipeline
struct game_ratios
{
    game_ratios (void) = default;

    game_ratios (float ppm, float scale, float highdpi)
        : ppm(ppm)
        , ppm_base_scale(scale)
        , ppm_highdpi_scale(highdpi)
    {
         this->base_to_world = (1.f / this->ppm);
         this->base_to_screen = this->ppm_base_scale * this->ppm_highdpi_scale;
         this->world_to_screen = this->ppm * this->base_to_screen;
         this->screen_to_world = (1.f / this->world_to_screen);
    }

    float ppm = 0.f;
    float ppm_base_scale = 0.f;
    float ppm_highdpi_scale = 0.f;

    float base_to_world = 0.f;
    float base_to_screen = 0.f;
    float world_to_screen = 0.f;
    float screen_to_world = 0.f;
};

struct chrono_globals
{
    rdge::Game* game;
    rdge::PackFile* pack;

    game_ratios ratios;

    //! \struct custom_event_data
    //! \details Stores the IDs generated by SDL to designate different custom
    //!          events.  You use an ID when pushing a custom event on the queue
    //!          and should be interpreted on a subsequent event invocation.
    perch::CustomEventTypeArray<rdge::uint32> custom_events;
};

extern chrono_globals g_game;
