/************************************************************/
/**              File generated by asset_packer            **/
/************************************************************/

// Created: Tue Jan  2 00:00:40 2018
// Version: 0

#pragma once

enum rdge_asset_pack_table
{
    rdge_asset_surface_animals = 0,
    rdge_asset_surface_overworld_bg = 1,
    rdge_asset_surface_overworld_obj = 2,
    rdge_asset_surface_player = 3,
    rdge_asset_spritesheet_animals = 4,
    rdge_asset_spritesheet_overworld_obj = 5,
    rdge_asset_spritesheet_player = 6,
    rdge_asset_tileset_overworld_bg = 7,
    rdge_asset_tilemap_overworld = 8,
}

enum animals_spritesheet_frames
{
    animals_frame_animals_mallard_baby_squint_front_1 = 0,
    animals_frame_animals_mallard_baby_squint_front_2 = 1,
    animals_frame_animals_mallard_baby_squint_side_1 = 2,
    animals_frame_animals_mallard_baby_squint_side_2 = 3,
    animals_frame_animals_mallard_baby_walk_back_1 = 4,
    animals_frame_animals_mallard_baby_walk_back_2 = 5,
    animals_frame_animals_mallard_baby_walk_front_1 = 6,
    animals_frame_animals_mallard_baby_walk_front_2 = 7,
    animals_frame_animals_mallard_baby_walk_side_1 = 8,
    animals_frame_animals_mallard_baby_walk_side_2 = 9,
    animals_frame_animals_seagull_fly_side_1 = 10,
    animals_frame_animals_seagull_fly_side_2 = 11,
    animals_frame_animals_seagull_fly_side_3 = 12,
    animals_frame_animals_seagull_fly_side_4 = 13,
    animals_frame_animals_seagull_fly_side_5 = 14,
    animals_frame_animals_seagull_fly_side_6 = 15,
    animals_frame_animals_seagull_fly_side_7 = 16,
}

enum animals_spritesheet_animations
{
    animals_animation_animals_mallard_baby_walk_front = 0,
    animals_animation_animals_mallard_baby_walk_back = 1,
    animals_animation_animals_mallard_baby_walk_right = 2,
    animals_animation_animals_mallard_baby_walk_left = 3,
    animals_animation_animals_seagull_fly_left = 4,
    animals_animation_animals_seagull_fly_right = 5,
}

enum overworld_obj_spritesheet_frames
{
    overworld_obj_frame_bush_01 = 2,
    overworld_obj_frame_bush_02 = 3,
    overworld_obj_frame_bush_03 = 4,
    overworld_obj_frame_chop_block_02 = 5,
    overworld_obj_frame_chop_block_03 = 6,
    overworld_obj_frame_flower_pot_01 = 1,
    overworld_obj_frame_stone_01 = 7,
    overworld_obj_frame_stone_02 = 8,
    overworld_obj_frame_tree_01 = 0,
}

enum player_spritesheet_frames
{
    player_frame_player_attack_back_1 = 0,
    player_frame_player_attack_back_2 = 1,
    player_frame_player_attack_back_3 = 2,
    player_frame_player_attack_back_4 = 3,
    player_frame_player_attack_back_5 = 4,
    player_frame_player_attack_front_1 = 5,
    player_frame_player_attack_front_2 = 6,
    player_frame_player_attack_front_3 = 7,
    player_frame_player_attack_front_4 = 8,
    player_frame_player_attack_front_5 = 9,
    player_frame_player_attack_side_1 = 10,
    player_frame_player_attack_side_2 = 11,
    player_frame_player_attack_side_3 = 12,
    player_frame_player_attack_side_4 = 13,
    player_frame_player_attack_side_5 = 14,
    player_frame_player_fight_idle_back_1 = 15,
    player_frame_player_fight_idle_back_2 = 16,
    player_frame_player_fight_idle_back_3 = 17,
    player_frame_player_fight_idle_front_1 = 18,
    player_frame_player_fight_idle_front_2 = 19,
    player_frame_player_fight_idle_front_3 = 20,
    player_frame_player_fight_idle_side_1 = 21,
    player_frame_player_fight_idle_side_2 = 22,
    player_frame_player_fight_idle_side_3 = 23,
    player_frame_player_idle_back_1 = 24,
    player_frame_player_idle_front_1 = 25,
    player_frame_player_idle_front_2 = 26,
    player_frame_player_idle_front_3 = 27,
    player_frame_player_idle_side_1 = 28,
    player_frame_player_idle_side_2 = 29,
    player_frame_player_idle_side_3 = 30,
    player_frame_player_run_back_1 = 31,
    player_frame_player_run_back_2 = 32,
    player_frame_player_run_front_1 = 33,
    player_frame_player_run_front_2 = 34,
    player_frame_player_run_side_1 = 35,
    player_frame_player_run_side_2 = 36,
    player_frame_player_sheathe_back_1 = 37,
    player_frame_player_sheathe_back_2 = 38,
    player_frame_player_sheathe_back_3 = 39,
    player_frame_player_sheathe_front_1 = 40,
    player_frame_player_sheathe_front_2 = 41,
    player_frame_player_sheathe_front_3 = 42,
    player_frame_player_sheathe_side_1 = 43,
    player_frame_player_sheathe_side_2 = 44,
    player_frame_player_sheathe_side_3 = 45,
    player_frame_player_walk_back_1 = 46,
    player_frame_player_walk_back_2 = 47,
    player_frame_player_walk_back_3 = 48,
    player_frame_player_walk_back_4 = 49,
    player_frame_player_walk_back_5 = 50,
    player_frame_player_walk_back_6 = 51,
    player_frame_player_walk_front_1 = 52,
    player_frame_player_walk_front_2 = 53,
    player_frame_player_walk_front_3 = 54,
    player_frame_player_walk_front_4 = 55,
    player_frame_player_walk_front_5 = 56,
    player_frame_player_walk_front_6 = 57,
    player_frame_player_walk_side_1 = 58,
    player_frame_player_walk_side_2 = 59,
    player_frame_player_walk_side_3 = 60,
    player_frame_player_walk_side_4 = 61,
    player_frame_player_walk_side_5 = 62,
    player_frame_player_walk_side_6 = 63,
}

enum player_spritesheet_animations
{
    player_animation_player_idle_front = 0,
    player_animation_player_idle_back = 1,
    player_animation_player_idle_right = 2,
    player_animation_player_idle_left = 3,
    player_animation_player_walk_front = 4,
    player_animation_player_walk_back = 5,
    player_animation_player_walk_right = 6,
    player_animation_player_walk_left = 7,
    player_animation_player_run_front = 8,
    player_animation_player_run_back = 9,
    player_animation_player_run_right = 10,
    player_animation_player_run_left = 11,
    player_animation_player_sheathe_front = 12,
    player_animation_player_sheathe_back = 13,
    player_animation_player_sheathe_right = 14,
    player_animation_player_sheathe_left = 15,
    player_animation_player_fight_idle_front = 16,
    player_animation_player_fight_idle_back = 17,
    player_animation_player_fight_idle_right = 18,
    player_animation_player_fight_idle_left = 19,
    player_animation_player_attack_front = 20,
    player_animation_player_attack_back = 21,
    player_animation_player_attack_right = 22,
    player_animation_player_attack_left = 23,
}

