/************************************************************/
/**              File generated by asset_packer            **/
/************************************************************/

// Created: 10/06/2017
// Version: 0

#pragma once

enum chrono_asset_pack_table
{
    chrono_asset_surface_enemies = 0,
    chrono_asset_surface_environment = 1,
    chrono_asset_surface_overworld = 2,
    chrono_asset_surface_player = 3,
    chrono_asset_spritesheet_enemies = 4,
    chrono_asset_spritesheet_environment = 5,
    chrono_asset_spritesheet_player = 6,
    chrono_asset_tilemap_overworld = 7,
};

enum enemies_spritesheet_regions
{
    enemies_region_duck_front_1 = 0,
    enemies_region_duck_front_2 = 1,
    enemies_region_duck_side_1 = 2,
    enemies_region_duck_side_2 = 3,
    enemies_region_duck_back_1 = 4,
    enemies_region_duck_back_2 = 5,
};

enum enemies_spritesheet_animations
{
    enemies_animation_duck_front = 0,
    enemies_animation_duck_back = 1,
    enemies_animation_duck_right = 2,
    enemies_animation_duck_left = 3,
};

enum environment_spritesheet_regions
{
    environment_region_dirt = 0,
    environment_region_weed1 = 1,
    environment_region_rock1 = 2,
};

enum player_spritesheet_regions
{
    player_region_idle_front_1 = 0,
    player_region_idle_front_2 = 1,
    player_region_idle_front_3 = 2,
    player_region_idle_back = 3,
    player_region_idle_side_1 = 4,
    player_region_idle_side_2 = 5,
    player_region_idle_side_3 = 6,
    player_region_walk_front_1 = 7,
    player_region_walk_front_2 = 8,
    player_region_walk_front_3 = 9,
    player_region_walk_front_4 = 10,
    player_region_walk_front_5 = 11,
    player_region_walk_front_6 = 12,
    player_region_walk_back_1 = 13,
    player_region_walk_back_2 = 14,
    player_region_walk_back_3 = 15,
    player_region_walk_back_4 = 16,
    player_region_walk_back_5 = 17,
    player_region_walk_back_6 = 18,
    player_region_walk_side_1 = 19,
    player_region_walk_side_2 = 20,
    player_region_walk_side_3 = 21,
    player_region_walk_side_4 = 22,
    player_region_walk_side_5 = 23,
    player_region_walk_side_6 = 24,
    player_region_run_front_1 = 25,
    player_region_run_front_2 = 26,
    player_region_run_back_1 = 27,
    player_region_run_back_2 = 28,
    player_region_run_side_1 = 29,
    player_region_run_side_2 = 30,
    player_region_sheathe_front_1 = 31,
    player_region_sheathe_front_2 = 32,
    player_region_sheathe_front_3 = 33,
    player_region_fight_stance_front_1 = 34,
    player_region_fight_stance_front_2 = 35,
    player_region_fight_stance_front_3 = 36,
    player_region_sheathe_back_1 = 37,
    player_region_sheathe_back_2 = 38,
    player_region_sheathe_back_3 = 39,
    player_region_fight_stance_back_1 = 40,
    player_region_fight_stance_back_2 = 41,
    player_region_fight_stance_back_3 = 42,
    player_region_sheathe_side_1 = 43,
    player_region_sheathe_side_2 = 44,
    player_region_sheathe_side_3 = 45,
    player_region_fight_stance_side_1 = 46,
    player_region_fight_stance_side_2 = 47,
    player_region_fight_stance_side_3 = 48,
    player_region_attack_front_1 = 49,
    player_region_attack_front_2 = 50,
    player_region_attack_front_3 = 51,
    player_region_attack_front_4 = 52,
    player_region_attack_front_5 = 53,
    player_region_attack_back_1 = 54,
    player_region_attack_back_2 = 55,
    player_region_attack_back_3 = 56,
    player_region_attack_back_4 = 57,
    player_region_attack_back_5 = 58,
    player_region_attack_side_1 = 59,
    player_region_attack_side_2 = 60,
    player_region_attack_side_3 = 61,
    player_region_attack_side_4 = 62,
    player_region_attack_side_5 = 63,
};

enum player_spritesheet_animations
{
    player_animation_idle_front = 0,
    player_animation_idle_back = 1,
    player_animation_idle_right = 2,
    player_animation_idle_left = 3,
    player_animation_walk_front = 4,
    player_animation_walk_back = 5,
    player_animation_walk_right = 6,
    player_animation_walk_left = 7,
    player_animation_run_front = 8,
    player_animation_run_back = 9,
    player_animation_run_right = 10,
    player_animation_run_left = 11,
    player_animation_sheathe_front = 12,
    player_animation_sheathe_back = 13,
    player_animation_sheathe_right = 14,
    player_animation_sheathe_left = 15,
    player_animation_fight_stance_front = 16,
    player_animation_fight_stance_back = 17,
    player_animation_fight_stance_right = 18,
    player_animation_fight_stance_left = 19,
    player_animation_attack_front = 20,
    player_animation_attack_back = 21,
    player_animation_attack_right = 22,
    player_animation_attack_left = 23,
};
